port: 7890
socks-port: 1080 # SOCKS5代理端口，DNS请求会中转
redir-port: 3333 # 透明代理端口
mode: rule
allow-lan: true

# allow-lan=true时,最好设置内网访问IP,关闭IPv6监听
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 addres
bind-address: '*'
# 不使用IPv6地址(配合上面的bind-address)
ipv6: true

external-controller: 0.0.0.0:9090
external-ui: /koolshare/clash/dashboard/
secret: route


dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://dns.cloudflare.com/dns-query
    - tls://dns.google:853
    - https://1.1.1.1/dns-query
    - https://public.dns.iij.jp/dns-query
    - https://jp.tiar.app/dns-query
    - https://jp.tiarap.org/dns-query
    - tls://dot.tiar.app
  fake-ip-filter:
    - +.*
experimental:
  sniff-tls-sni: true
profile:
  store-selected: true

# 保留的proxy节点列表(启动配置文件不包含任何节点信息,节点信息通过 proxy-provider 提供)
proxies: []

proxy-providers:
  proxy-provider-http001:
    type: http
    path: ./providers/provider_http_001.yaml
    url: https://raw.githubusercontent.com/vxiaov/free_proxies/main/clash/clash.provider.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  proxy-provider-diy:
    type: file
    path: ./providers/provider_diy.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

proxy-groups:
  - name: 个人节点组
    type: select
    url: http://cp.cloudflare.com/generate_204
    interval: 600
    tolerance: 150
    use:
      - proxy-provider-diy
  - name: AutoUrlTest节点组
    type: url-test
    proxies:
    use:
      - proxy-provider-http001
      - proxy-provider-diy
    url: http://cp.cloudflare.com/generate_204
    interval: 600
    tolerance: 150
  - name: 订阅节点组
    type: select
    use:
      - proxy-provider-http001
    url: http://cp.cloudflare.com/generate_204
    interval: 600
    tolerance: 150
  - name: Relay-in
    type: select
    proxies:
      - DIRECT
      - 个人节点组
  - name: Relay-out
    type: select
    proxies:
      - DIRECT
      - 订阅节点组
      - 个人节点组
  - name: Relay中继节点组
    type: relay
    proxies:
      - Relay-in
      - Relay-out
  - name: ⭐默认节点组⭐
    type: select
    proxies:
      - AutoUrlTest节点组
      - 个人节点组
      - 订阅节点组
      - DIRECT
      - Relay中继节点组
  - name: Domestic
    type: select
    proxies:
      - DIRECT
      - ⭐默认节点组⭐
  - name: Others
    type: select
    proxies:
      - ⭐默认节点组⭐
      - DIRECT
      - Domestic
  - name: Microsoft
    type: select
    proxies:
      - DIRECT
      - ⭐默认节点组⭐
  - name: ChatGPT
    type: select
    proxies:
      - ⭐默认节点组⭐
      - DIRECT
      - Relay中继节点组
  - name: Apple
    type: select
    proxies:
      - DIRECT
      - ⭐默认节点组⭐
  - name: Apple TV
    type: select
    proxies:
      - ⭐默认节点组⭐
      - DIRECT
  - name: Google FCM
    type: select
    proxies:
      - DIRECT
      - ⭐默认节点组⭐
  - name: Scholar
    type: select
    proxies:
      - DIRECT
      - ⭐默认节点组⭐
  - name: Bilibili
    type: select
    proxies:
      - Asian TV
      - DIRECT
  - name: Bahamut
    type: select
    proxies:
      - Global TV
      - DIRECT
  - name: HBO Max
    type: select
    proxies:
      - Global TV
      - DIRECT
  - name: HBO Go
    type: select
    proxies:
      - Global TV
      - DIRECT
  - name: Pornhub
    type: select
    proxies:
      - Global TV
      - DIRECT
  - name: Netflix
    type: select
    proxies:
      - Global TV
      - DIRECT
  - name: Disney
    type: select
    proxies:
      - Global TV
      - DIRECT
  - name: Youtube
    type: select
    disable-udp: true
    proxies:
      - Global TV
      - DIRECT
  - name: Discovery Plus
    type: select
    proxies:
      - Global TV
      - DIRECT
  - name: DAZN
    type: select
    proxies:
      - Global TV
      - DIRECT
  - name: Spotify
    type: select
    proxies:
      - Global TV
      - DIRECT
  - name: Steam
    type: select
    proxies:
      - DIRECT
      - ⭐默认节点组⭐
  - name: AdBlock
    type: select
    proxies:
      - REJECT
      - DIRECT
      - ⭐默认节点组⭐
  - name: Asian TV
    type: select
    proxies:
      - DIRECT
      - ⭐默认节点组⭐
  - name: Global TV
    type: select
    proxies:
      - ⭐默认节点组⭐
      - DIRECT
  - name: Speedtest
    type: select
    proxies:
      - ⭐默认节点组⭐
      - DIRECT
  - name: Telegram
    type: select
    proxies:
      - ⭐默认节点组⭐
      - DIRECT
  - name: Crypto
    type: select
    proxies:
      - ⭐默认节点组⭐
      - DIRECT
  - name: Discord
    type: select
    proxies:
      - ⭐默认节点组⭐
      - DIRECT
  - name: PayPal
    type: select
    proxies:
      - DIRECT
      - ⭐默认节点组⭐

rule-providers:
  Reject:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Reject.yaml
    path: ./ruleset/Reject
    interval: 86400
  Special:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Special.yaml
    path: ./ruleset/Special
    interval: 86400
  Netflix:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Netflix.yaml
    path: ./ruleset/Netflix
    interval: 86400
  Spotify:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Spotify.yaml
    path: ./ruleset/Spotify
    interval: 86400
  YouTube:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/YouTube.yaml
    path: ./ruleset/YouTube
    interval: 86400
  Bilibili:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Bilibili.yaml
    path: ./ruleset/Bilibili
    interval: 86400
  IQ:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/IQ.yaml
    path: ./ruleset/IQI
    interval: 86400
  IQIYI:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/IQIYI.yaml
    path: ./ruleset/IQYI
    interval: 86400
  Letv:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Letv.yaml
    path: ./ruleset/Letv
    interval: 86400
  Netease Music:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Netease%20Music.yaml
    path: ./ruleset/Netease_Music
    interval: 86400
  Tencent Video:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Tencent%20Video.yaml
    path: ./ruleset/Tencent_Video
    interval: 86400
  Youku:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Youku.yaml
    path: ./ruleset/Youku
    interval: 86400
  WeTV:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/WeTV.yaml
    path: ./ruleset/WeTV
    interval: 86400
  ABC:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/ABC.yaml
    path: ./ruleset/ABC
    interval: 86400
  Abema TV:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Abema%20TV.yaml
    path: ./ruleset/Abema_TV
    interval: 86400
  Amazon:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Amazon.yaml
    path: ./ruleset/Amazon
    interval: 86400
  Apple Music:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Apple%20Music.yaml
    path: ./ruleset/Apple_Music
    interval: 86400
  Apple News:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Apple%20News.yaml
    path: ./ruleset/Apple_News
    interval: 86400
  Apple TV:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Apple%20TV.yaml
    path: ./ruleset/Apple_TV
    interval: 86400
  Bahamut:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Bahamut.yaml
    path: ./ruleset/Bahamut
    interval: 86400
  BBC iPlayer:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/BBC%20iPlayer.yaml
    path: ./ruleset/BBC_iPlayer
    interval: 86400
  DAZN:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/DAZN.yaml
    path: ./ruleset/DAZN
    interval: 86400
  Discovery Plus:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Discovery%20Plus.yaml
    path: ./ruleset/Discovery_Plus
    interval: 86400
  Disney Plus:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Disney%20Plus.yaml
    path: ./ruleset/Disney_Plus
    interval: 86400
  encoreTVB:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/encoreTVB.yaml
    path: ./ruleset/encoreTVB
    interval: 86400
  F1 TV:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/F1%20TV.yaml
    path: ./ruleset/F1_TV
    interval: 86400
  Fox Now:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Fox%20Now.yaml
    path: ./ruleset/Fox_Now
    interval: 86400
  Fox+:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Fox%2B.yaml
    path: ./ruleset/Fox+
    interval: 86400
  HBO Go:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/HBO%20Go.yaml
    path: ./ruleset/HBO_Go
    interval: 86400
  HBO Max:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/HBO%20Max.yaml
    path: ./ruleset/HBO_Max
    interval: 86400
  Hulu Japan:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Hulu%20Japan.yaml
    path: ./ruleset/Hulu_Japan
    interval: 86400
  Hulu:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Hulu.yaml
    path: ./ruleset/Hulu
    interval: 86400
  Japonx:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Japonx.yaml
    path: ./ruleset/Japonx
    interval: 86400
  JOOX:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/JOOX.yaml
    path: ./ruleset/JOOX
    interval: 86400
  KKBOX:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/KKBOX.yaml
    path: ./ruleset/KKBOX
    interval: 86400
  KKTV:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/KKTV.yaml
    path: ./ruleset/KKTV
    interval: 86400
  Line TV:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Line%20TV.yaml
    path: ./ruleset/Line_TV
    interval: 86400
  myTV SUPER:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/myTV%20SUPER.yaml
    path: ./ruleset/myTV_SUPER
    interval: 86400
  Niconico:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Niconico.yaml
    path: ./ruleset/Niconico
    interval: 86400
  Pandora:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Pandora.yaml
    path: ./ruleset/Pandora
    interval: 86400
  PBS:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/PBS.yaml
    path: ./ruleset/PBS
    interval: 86400
  Pornhub:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Pornhub.yaml
    path: ./ruleset/Pornhub
    interval: 86400
  Soundcloud:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Soundcloud.yaml
    path: ./ruleset/Soundcloud
    interval: 86400
  ViuTV:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/ViuTV.yaml
    path: ./ruleset/ViuTV
    interval: 86400
  Telegram:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Telegram.yaml
    path: ./ruleset/Telegram
    interval: 86400
  Crypto:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Crypto.yaml
    path: ./ruleset/Crypto
    interval: 86400
  Discord:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Discord.yaml
    path: ./ruleset/Discord
    interval: 86400
  Steam:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Steam.yaml
    path: ./ruleset/Steam
    interval: 86400
  Speedtest:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Speedtest.yaml
    path: ./ruleset/Speedtest
    interval: 86400
  PayPal:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/PayPal.yaml
    path: ./ruleset/PayPal
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Microsoft.yaml
    path: ./ruleset/Microsoft
    interval: 86400
  ChatGPT:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/ChatGPT.yaml
    path: ./ruleset/ChatGPT
    interval: 86400
  PROXY:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Proxy.yaml
    path: ./ruleset/Proxy
    interval: 86400
  Domestic:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Domestic.yaml
    path: ./ruleset/Domestic
    interval: 86400
  Apple:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Apple.yaml
    path: ./ruleset/Apple
    interval: 86400
  Google FCM:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Google%20FCM.yaml
    path: ./ruleset/Google FCM
    interval: 86400
  Scholar:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Scholar.yaml
    path: ./ruleset/Scholar
    interval: 86400
  Domestic IPs:
    type: http
    behavior: ipcidr
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Domestic%20IPs.yaml
    path: ./ruleset/Domestic_IPs
    interval: 86400
  LAN:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/LAN.yaml
    path: ./ruleset/LAN
    interval: 86400
  MyBlacklist:
    type: file
    behavior: classical
    path: ./ruleset/my_blacklist.yaml
  MyWhitelist:
    type: file
    behavior: classical
    path: ./ruleset/my_whitelist.yaml

rules:
  - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  - RULE-SET,MyWhitelist,DIRECT
  - RULE-SET,MyBlacklist,⭐默认节点组⭐
  - RULE-SET,Reject,AdBlock
  - RULE-SET,Special,DIRECT
  - RULE-SET,Netflix,Netflix
  - RULE-SET,Spotify,Spotify
  - RULE-SET,YouTube,Youtube
  - RULE-SET,Disney Plus,Disney
  - RULE-SET,Bilibili,Bilibili
  - RULE-SET,IQ,Asian TV
  - RULE-SET,IQIYI,Asian TV
  - RULE-SET,Letv,Asian TV
  - RULE-SET,Netease Music,Asian TV
  - RULE-SET,Tencent Video,Asian TV
  - RULE-SET,Youku,Asian TV
  - RULE-SET,WeTV,Asian TV
  - RULE-SET,ABC,Global TV
  - RULE-SET,Abema TV,Global TV
  - RULE-SET,Amazon,Global TV
  - RULE-SET,Bahamut,Bahamut
  - RULE-SET,BBC iPlayer,Global TV
  - RULE-SET,DAZN,DAZN
  - RULE-SET,Discovery Plus,Discovery Plus
  - RULE-SET,encoreTVB,Global TV
  - RULE-SET,F1 TV,Global TV
  - RULE-SET,Fox Now,Global TV
  - RULE-SET,Fox+,Global TV
  - RULE-SET,HBO Go,HBO Go
  - RULE-SET,HBO Max,HBO Max
  - RULE-SET,Hulu Japan,Global TV
  - RULE-SET,Hulu,Global TV
  - RULE-SET,Japonx,Global TV
  - RULE-SET,JOOX,Global TV
  - RULE-SET,KKBOX,Global TV
  - RULE-SET,KKTV,Global TV
  - RULE-SET,Line TV,Global TV
  - RULE-SET,myTV SUPER,Global TV
  - RULE-SET,Niconico,Global TV
  - RULE-SET,Pandora,Global TV
  - RULE-SET,PBS,Global TV
  - RULE-SET,Pornhub,Pornhub
  - RULE-SET,Soundcloud,Global TV
  - RULE-SET,ViuTV,Global TV
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Crypto,Crypto
  - RULE-SET,Discord,Discord
  - RULE-SET,Steam,Steam
  - RULE-SET,Speedtest,Speedtest
  - RULE-SET,PayPal,PayPal
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,ChatGPT,ChatGPT
  - RULE-SET,Apple Music,Apple TV
  - RULE-SET,Apple News,Apple TV
  - RULE-SET,Apple TV,Apple TV
  - RULE-SET,Apple,Apple
  - RULE-SET,Google FCM,Google FCM
  - RULE-SET,Scholar,Scholar
  - RULE-SET,PROXY,⭐默认节点组⭐
  - RULE-SET,Domestic,Domestic
  - RULE-SET,Domestic IPs,Domestic
  - RULE-SET,LAN,DIRECT
  - GEOIP,CN,Domestic
  - MATCH,Others
